### ISSUE TITLE
Complete Code

### ISSUE THREAD

**Issue by ishwarbb** [leobertolazzi/soft-syllogistic-reasoner#1]
Hi @leobertolazzi ,

I noticed that the rest of the code mentioned in the paper has not been made public. Could you kindly share it?

Additionally, would it be possible to release the dataset as promised in the paper? Constructing a believable/unbelievable dataset is quite time-consuming, and having access to it would be incredibly helpful.

Thank you!

**Comment by leobertolazzi** [comment]
Hi @ishwarbb,

Thank you for your interest in the code and data related to the paper. I will present this at EMNLP in mid-November, and I can guarantee that everything will be available by then.

I am currently cleaning it up from additional experiments that were ultimately not included in the paper, and I plan to release everything in the coming weeks.

Cheers!

**Comment by ishwarbb** [comment]
Thank you for your quick reply! I appreciate the update and look forward to accessing the code and data when it's ready.

Best regards!
